// lib/games-data.ts
// Games database — expand this over time. More games = more rankable pages.
// Each game generates: /games/[slug], /fps/[gameId]/[cpuId]/[gpuId] (CPUs × GPUs × games)

export interface Game {
  id: string
  name: string
  genre: string
  releaseYear: number
  publisher: string
  // FPS at REFERENCE BUILD (cpuScore=75, gpuScore=75) — medium-high settings
  baseFps: {
    '1080p': number
    '1440p': number
    '4k': number
  }
  // 0 = fully CPU-bound, 1 = fully GPU-bound
  // Higher res shifts every game toward GPU
  gpuBound: number
  requirements: {
    minimum:     { cpuScore: number; gpuScore: number; ramGb: number }
    recommended: { cpuScore: number; gpuScore: number; ramGb: number }
    ultra:       { cpuScore: number; gpuScore: number; ramGb: number }
  }
  tags: string[]
  isCompetitive: boolean // esports titles — players prioritize high FPS
  hasRayTracing: boolean
  apiSupport: ('DirectX 11' | 'DirectX 12' | 'Vulkan' | 'OpenGL')[]
}

export const GAMES: Game[] = [
  // ─── AAA Demanding ──────────────────────────────────────────────────────────
  {
    id: 'cyberpunk-2077',
    name: 'Cyberpunk 2077',
    genre: 'RPG / Open World',
    releaseYear: 2020,
    publisher: 'CD Projekt Red',
    baseFps: { '1080p': 82, '1440p': 55, '4k': 28 },
    gpuBound: 0.88,
    requirements: {
      minimum:     { cpuScore: 38, gpuScore: 32, ramGb: 8 },
      recommended: { cpuScore: 62, gpuScore: 68, ramGb: 16 },
      ultra:       { cpuScore: 88, gpuScore: 92, ramGb: 32 },
    },
    tags: ['open-world', 'rpg', 'ray-tracing', 'demanding', 'single-player'],
    isCompetitive: false,
    hasRayTracing: true,
    apiSupport: ['DirectX 12', 'Vulkan'],
  },
  {
    id: 'red-dead-redemption-2',
    name: 'Red Dead Redemption 2',
    genre: 'Action / Open World',
    releaseYear: 2019,
    publisher: 'Rockstar Games',
    baseFps: { '1080p': 72, '1440p': 50, '4k': 26 },
    gpuBound: 0.82,
    requirements: {
      minimum:     { cpuScore: 35, gpuScore: 30, ramGb: 8 },
      recommended: { cpuScore: 60, gpuScore: 65, ramGb: 16 },
      ultra:       { cpuScore: 82, gpuScore: 88, ramGb: 32 },
    },
    tags: ['open-world', 'action', 'demanding', 'single-player'],
    isCompetitive: false,
    hasRayTracing: false,
    apiSupport: ['Vulkan'],
  },
  {
    id: 'alan-wake-2',
    name: 'Alan Wake 2',
    genre: 'Survival Horror',
    releaseYear: 2023,
    publisher: 'Remedy Entertainment',
    baseFps: { '1080p': 58, '1440p': 38, '4k': 20 },
    gpuBound: 0.90,
    requirements: {
      minimum:     { cpuScore: 55, gpuScore: 60, ramGb: 16 },
      recommended: { cpuScore: 75, gpuScore: 80, ramGb: 16 },
      ultra:       { cpuScore: 90, gpuScore: 95, ramGb: 32 },
    },
    tags: ['horror', 'ray-tracing', 'demanding', 'path-tracing', 'single-player'],
    isCompetitive: false,
    hasRayTracing: true,
    apiSupport: ['DirectX 12'],
  },
  {
    id: 'microsoft-flight-simulator',
    name: 'Microsoft Flight Simulator 2024',
    genre: 'Simulation',
    releaseYear: 2024,
    publisher: 'Asobo Studio',
    baseFps: { '1080p': 48, '1440p': 32, '4k': 17 },
    gpuBound: 0.70,
    requirements: {
      minimum:     { cpuScore: 50, gpuScore: 45, ramGb: 8 },
      recommended: { cpuScore: 72, gpuScore: 75, ramGb: 16 },
      ultra:       { cpuScore: 90, gpuScore: 92, ramGb: 32 },
    },
    tags: ['simulation', 'cpu-intensive', 'demanding', 'multiplayer'],
    isCompetitive: false,
    hasRayTracing: false,
    apiSupport: ['DirectX 12'],
  },
  {
    id: 'starfield',
    name: 'Starfield',
    genre: 'RPG / Sci-Fi',
    releaseYear: 2023,
    publisher: 'Bethesda',
    baseFps: { '1080p': 68, '1440p': 48, '4k': 26 },
    gpuBound: 0.78,
    requirements: {
      minimum:     { cpuScore: 48, gpuScore: 45, ramGb: 16 },
      recommended: { cpuScore: 70, gpuScore: 72, ramGb: 16 },
      ultra:       { cpuScore: 88, gpuScore: 90, ramGb: 32 },
    },
    tags: ['rpg', 'sci-fi', 'open-world', 'single-player'],
    isCompetitive: false,
    hasRayTracing: false,
    apiSupport: ['DirectX 12'],
  },
  {
    id: 'hogwarts-legacy',
    name: 'Hogwarts Legacy',
    genre: 'RPG / Action',
    releaseYear: 2023,
    publisher: 'WB Games',
    baseFps: { '1080p': 76, '1440p': 52, '4k': 27 },
    gpuBound: 0.84,
    requirements: {
      minimum:     { cpuScore: 40, gpuScore: 38, ramGb: 8 },
      recommended: { cpuScore: 65, gpuScore: 70, ramGb: 16 },
      ultra:       { cpuScore: 85, gpuScore: 90, ramGb: 32 },
    },
    tags: ['rpg', 'action', 'fantasy', 'single-player'],
    isCompetitive: false,
    hasRayTracing: true,
    apiSupport: ['DirectX 12'],
  },
  {
    id: 'avatar-frontiers',
    name: 'Avatar: Frontiers of Pandora',
    genre: 'Action / Open World',
    releaseYear: 2023,
    publisher: 'Ubisoft',
    baseFps: { '1080p': 62, '1440p': 42, '4k': 22 },
    gpuBound: 0.87,
    requirements: {
      minimum:     { cpuScore: 52, gpuScore: 55, ramGb: 16 },
      recommended: { cpuScore: 75, gpuScore: 78, ramGb: 16 },
      ultra:       { cpuScore: 90, gpuScore: 95, ramGb: 32 },
    },
    tags: ['open-world', 'action', 'demanding', 'single-player'],
    isCompetitive: false,
    hasRayTracing: true,
    apiSupport: ['DirectX 12'],
  },
  {
    id: 'helldivers-2',
    name: 'Helldivers 2',
    genre: 'Third-Person Shooter',
    releaseYear: 2024,
    publisher: 'Arrowhead Game Studios',
    baseFps: { '1080p': 72, '1440p': 50, '4k': 26 },
    gpuBound: 0.80,
    requirements: {
      minimum:     { cpuScore: 45, gpuScore: 50, ramGb: 8 },
      recommended: { cpuScore: 68, gpuScore: 68, ramGb: 16 },
      ultra:       { cpuScore: 85, gpuScore: 85, ramGb: 32 },
    },
    tags: ['shooter', 'co-op', 'third-person', 'multiplayer'],
    isCompetitive: false,
    hasRayTracing: false,
    apiSupport: ['DirectX 12'],
  },
  {
    id: 'baldurs-gate-3',
    name: "Baldur's Gate 3",
    genre: 'RPG / Turn-Based',
    releaseYear: 2023,
    publisher: 'Larian Studios',
    baseFps: { '1080p': 82, '1440p': 58, '4k': 30 },
    gpuBound: 0.75,
    requirements: {
      minimum:     { cpuScore: 35, gpuScore: 30, ramGb: 8 },
      recommended: { cpuScore: 58, gpuScore: 60, ramGb: 16 },
      ultra:       { cpuScore: 80, gpuScore: 82, ramGb: 32 },
    },
    tags: ['rpg', 'turn-based', 'fantasy', 'single-player', 'co-op'],
    isCompetitive: false,
    hasRayTracing: false,
    apiSupport: ['Vulkan', 'DirectX 11'],
  },
  {
    id: 'elden-ring',
    name: 'Elden Ring',
    genre: 'Action RPG / Soulslike',
    releaseYear: 2022,
    publisher: 'FromSoftware',
    baseFps: { '1080p': 98, '1440p': 72, '4k': 40 },
    gpuBound: 0.78,
    requirements: {
      minimum:     { cpuScore: 35, gpuScore: 30, ramGb: 12 },
      recommended: { cpuScore: 60, gpuScore: 62, ramGb: 16 },
      ultra:       { cpuScore: 80, gpuScore: 80, ramGb: 32 },
    },
    tags: ['action', 'rpg', 'soulslike', 'single-player'],
    isCompetitive: false,
    hasRayTracing: false,
    apiSupport: ['DirectX 12'],
  },
  {
    id: 'god-of-war',
    name: 'God of War',
    genre: 'Action / Adventure',
    releaseYear: 2022,
    publisher: 'Santa Monica Studio',
    baseFps: { '1080p': 102, '1440p': 72, '4k': 38 },
    gpuBound: 0.80,
    requirements: {
      minimum:     { cpuScore: 35, gpuScore: 30, ramGb: 8 },
      recommended: { cpuScore: 58, gpuScore: 60, ramGb: 16 },
      ultra:       { cpuScore: 82, gpuScore: 85, ramGb: 32 },
    },
    tags: ['action', 'adventure', 'single-player', 'narrative'],
    isCompetitive: false,
    hasRayTracing: false,
    apiSupport: ['DirectX 11', 'DirectX 12'],
  },
  {
    id: 'spider-man-remastered',
    name: "Marvel's Spider-Man Remastered",
    genre: 'Action / Open World',
    releaseYear: 2022,
    publisher: 'Insomniac Games',
    baseFps: { '1080p': 95, '1440p': 65, '4k': 34 },
    gpuBound: 0.82,
    requirements: {
      minimum:     { cpuScore: 35, gpuScore: 32, ramGb: 16 },
      recommended: { cpuScore: 60, gpuScore: 65, ramGb: 16 },
      ultra:       { cpuScore: 82, gpuScore: 88, ramGb: 32 },
    },
    tags: ['action', 'open-world', 'ray-tracing', 'single-player'],
    isCompetitive: false,
    hasRayTracing: true,
    apiSupport: ['DirectX 12'],
  },
  {
    id: 'the-witcher-3',
    name: 'The Witcher 3: Wild Hunt',
    genre: 'RPG / Open World',
    releaseYear: 2015,
    publisher: 'CD Projekt Red',
    baseFps: { '1080p': 95, '1440p': 65, '4k': 34 },
    gpuBound: 0.80,
    requirements: {
      minimum:     { cpuScore: 20, gpuScore: 18, ramGb: 6 },
      recommended: { cpuScore: 45, gpuScore: 42, ramGb: 8 },
      ultra:       { cpuScore: 75, gpuScore: 80, ramGb: 16 },
    },
    tags: ['rpg', 'open-world', 'fantasy', 'single-player', 'ray-tracing'],
    isCompetitive: false,
    hasRayTracing: true,
    apiSupport: ['DirectX 12', 'Vulkan'],
  },
  {
    id: 'gta-v',
    name: 'Grand Theft Auto V',
    genre: 'Action / Open World',
    releaseYear: 2013,
    publisher: 'Rockstar Games',
    baseFps: { '1080p': 125, '1440p': 88, '4k': 46 },
    gpuBound: 0.75,
    requirements: {
      minimum:     { cpuScore: 18, gpuScore: 15, ramGb: 4 },
      recommended: { cpuScore: 35, gpuScore: 32, ramGb: 8 },
      ultra:       { cpuScore: 60, gpuScore: 60, ramGb: 16 },
    },
    tags: ['open-world', 'action', 'multiplayer', 'classic'],
    isCompetitive: false,
    hasRayTracing: false,
    apiSupport: ['DirectX 11'],
  },
  {
    id: 'forza-horizon-5',
    name: 'Forza Horizon 5',
    genre: 'Racing',
    releaseYear: 2021,
    publisher: 'Playground Games',
    baseFps: { '1080p': 108, '1440p': 76, '4k': 40 },
    gpuBound: 0.82,
    requirements: {
      minimum:     { cpuScore: 28, gpuScore: 25, ramGb: 8 },
      recommended: { cpuScore: 55, gpuScore: 58, ramGb: 16 },
      ultra:       { cpuScore: 82, gpuScore: 88, ramGb: 16 },
    },
    tags: ['racing', 'open-world', 'single-player', 'multiplayer'],
    isCompetitive: false,
    hasRayTracing: true,
    apiSupport: ['DirectX 12'],
  },
  {
    id: 'diablo-iv',
    name: 'Diablo IV',
    genre: 'Action RPG / Hack and Slash',
    releaseYear: 2023,
    publisher: 'Blizzard Entertainment',
    baseFps: { '1080p': 105, '1440p': 72, '4k': 38 },
    gpuBound: 0.78,
    requirements: {
      minimum:     { cpuScore: 35, gpuScore: 30, ramGb: 8 },
      recommended: { cpuScore: 60, gpuScore: 60, ramGb: 32 },
      ultra:       { cpuScore: 80, gpuScore: 82, ramGb: 32 },
    },
    tags: ['arpg', 'hack-and-slash', 'dark-fantasy', 'multiplayer'],
    isCompetitive: false,
    hasRayTracing: false,
    apiSupport: ['DirectX 12'],
  },
  {
    id: 'palworld',
    name: 'Palworld',
    genre: 'Survival / Crafting',
    releaseYear: 2024,
    publisher: 'Pocket Pair',
    baseFps: { '1080p': 80, '1440p': 56, '4k': 30 },
    gpuBound: 0.75,
    requirements: {
      minimum:     { cpuScore: 40, gpuScore: 38, ramGb: 16 },
      recommended: { cpuScore: 65, gpuScore: 65, ramGb: 16 },
      ultra:       { cpuScore: 82, gpuScore: 82, ramGb: 32 },
    },
    tags: ['survival', 'crafting', 'open-world', 'multiplayer'],
    isCompetitive: false,
    hasRayTracing: false,
    apiSupport: ['DirectX 12'],
  },
  {
    id: 'the-last-of-us',
    name: 'The Last of Us Part I',
    genre: 'Action / Adventure',
    releaseYear: 2023,
    publisher: 'Naughty Dog',
    baseFps: { '1080p': 70, '1440p': 48, '4k': 25 },
    gpuBound: 0.84,
    requirements: {
      minimum:     { cpuScore: 48, gpuScore: 50, ramGb: 16 },
      recommended: { cpuScore: 72, gpuScore: 72, ramGb: 16 },
      ultra:       { cpuScore: 88, gpuScore: 90, ramGb: 32 },
    },
    tags: ['action', 'adventure', 'horror', 'single-player', 'narrative'],
    isCompetitive: false,
    hasRayTracing: false,
    apiSupport: ['DirectX 12'],
  },
  {
    id: 'control',
    name: 'Control Ultimate Edition',
    genre: 'Action / Third-Person',
    releaseYear: 2019,
    publisher: 'Remedy Entertainment',
    baseFps: { '1080p': 85, '1440p': 58, '4k': 30 },
    gpuBound: 0.85,
    requirements: {
      minimum:     { cpuScore: 32, gpuScore: 28, ramGb: 8 },
      recommended: { cpuScore: 55, gpuScore: 58, ramGb: 16 },
      ultra:       { cpuScore: 78, gpuScore: 82, ramGb: 16 },
    },
    tags: ['action', 'third-person', 'ray-tracing', 'single-player'],
    isCompetitive: false,
    hasRayTracing: true,
    apiSupport: ['DirectX 12'],
  },
  {
    id: 'death-stranding',
    name: 'Death Stranding',
    genre: 'Action / Adventure',
    releaseYear: 2020,
    publisher: 'Kojima Productions',
    baseFps: { '1080p': 105, '1440p': 72, '4k': 38 },
    gpuBound: 0.80,
    requirements: {
      minimum:     { cpuScore: 30, gpuScore: 28, ramGb: 8 },
      recommended: { cpuScore: 55, gpuScore: 55, ramGb: 8 },
      ultra:       { cpuScore: 78, gpuScore: 80, ramGb: 16 },
    },
    tags: ['action', 'adventure', 'sci-fi', 'single-player', 'narrative'],
    isCompetitive: false,
    hasRayTracing: false,
    apiSupport: ['DirectX 12'],
  },
  {
    id: 'metro-exodus',
    name: 'Metro Exodus Enhanced Edition',
    genre: 'FPS / Survival',
    releaseYear: 2021,
    publisher: '4A Games',
    baseFps: { '1080p': 72, '1440p': 50, '4k': 26 },
    gpuBound: 0.87,
    requirements: {
      minimum:     { cpuScore: 38, gpuScore: 42, ramGb: 8 },
      recommended: { cpuScore: 65, gpuScore: 70, ramGb: 16 },
      ultra:       { cpuScore: 85, gpuScore: 90, ramGb: 16 },
    },
    tags: ['fps', 'survival', 'ray-tracing', 'single-player', 'post-apocalyptic'],
    isCompetitive: false,
    hasRayTracing: true,
    apiSupport: ['Vulkan'],
  },
  {
    id: 'horizon-zero-dawn',
    name: 'Horizon Zero Dawn Remastered',
    genre: 'Action RPG / Open World',
    releaseYear: 2020,
    publisher: 'Guerrilla Games',
    baseFps: { '1080p': 100, '1440p': 68, '4k': 36 },
    gpuBound: 0.80,
    requirements: {
      minimum:     { cpuScore: 35, gpuScore: 32, ramGb: 8 },
      recommended: { cpuScore: 60, gpuScore: 62, ramGb: 16 },
      ultra:       { cpuScore: 82, gpuScore: 85, ramGb: 16 },
    },
    tags: ['action', 'rpg', 'open-world', 'sci-fi', 'single-player'],
    isCompetitive: false,
    hasRayTracing: false,
    apiSupport: ['DirectX 12'],
  },
  {
    id: 'assassins-creed-shadows',
    name: "Assassin's Creed Shadows",
    genre: 'Action / Open World',
    releaseYear: 2025,
    publisher: 'Ubisoft',
    baseFps: { '1080p': 68, '1440p': 46, '4k': 24 },
    gpuBound: 0.85,
    requirements: {
      minimum:     { cpuScore: 55, gpuScore: 58, ramGb: 16 },
      recommended: { cpuScore: 78, gpuScore: 80, ramGb: 16 },
      ultra:       { cpuScore: 92, gpuScore: 95, ramGb: 32 },
    },
    tags: ['action', 'open-world', 'stealth', 'single-player', 'demanding'],
    isCompetitive: false,
    hasRayTracing: true,
    apiSupport: ['DirectX 12'],
  },
  // ─── Competitive / Esports ──────────────────────────────────────────────────
  {
    id: 'valorant',
    name: 'Valorant',
    genre: 'Tactical FPS',
    releaseYear: 2020,
    publisher: 'Riot Games',
    baseFps: { '1080p': 420, '1440p': 310, '4k': 170 },
    gpuBound: 0.55,
    requirements: {
      minimum:     { cpuScore: 15, gpuScore: 12, ramGb: 4 },
      recommended: { cpuScore: 35, gpuScore: 28, ramGb: 8 },
      ultra:       { cpuScore: 60, gpuScore: 50, ramGb: 16 },
    },
    tags: ['fps', 'competitive', 'tactical', 'esports', 'multiplayer'],
    isCompetitive: true,
    hasRayTracing: false,
    apiSupport: ['DirectX 11'],
  },
  {
    id: 'counter-strike-2',
    name: 'Counter-Strike 2',
    genre: 'Tactical FPS',
    releaseYear: 2023,
    publisher: 'Valve',
    baseFps: { '1080p': 215, '1440p': 158, '4k': 85 },
    gpuBound: 0.60,
    requirements: {
      minimum:     { cpuScore: 18, gpuScore: 15, ramGb: 8 },
      recommended: { cpuScore: 38, gpuScore: 35, ramGb: 16 },
      ultra:       { cpuScore: 68, gpuScore: 60, ramGb: 16 },
    },
    tags: ['fps', 'competitive', 'tactical', 'esports', 'multiplayer'],
    isCompetitive: true,
    hasRayTracing: false,
    apiSupport: ['Vulkan', 'DirectX 11'],
  },
  {
    id: 'apex-legends',
    name: 'Apex Legends',
    genre: 'Battle Royale FPS',
    releaseYear: 2019,
    publisher: 'Respawn Entertainment',
    baseFps: { '1080p': 205, '1440p': 148, '4k': 78 },
    gpuBound: 0.65,
    requirements: {
      minimum:     { cpuScore: 20, gpuScore: 18, ramGb: 8 },
      recommended: { cpuScore: 42, gpuScore: 40, ramGb: 16 },
      ultra:       { cpuScore: 68, gpuScore: 65, ramGb: 16 },
    },
    tags: ['fps', 'battle-royale', 'competitive', 'esports', 'multiplayer'],
    isCompetitive: true,
    hasRayTracing: false,
    apiSupport: ['DirectX 11'],
  },
  {
    id: 'fortnite',
    name: 'Fortnite',
    genre: 'Battle Royale',
    releaseYear: 2017,
    publisher: 'Epic Games',
    baseFps: { '1080p': 155, '1440p': 108, '4k': 56 },
    gpuBound: 0.70,
    requirements: {
      minimum:     { cpuScore: 18, gpuScore: 15, ramGb: 8 },
      recommended: { cpuScore: 40, gpuScore: 38, ramGb: 16 },
      ultra:       { cpuScore: 70, gpuScore: 72, ramGb: 16 },
    },
    tags: ['battle-royale', 'competitive', 'multiplayer', 'cross-platform'],
    isCompetitive: true,
    hasRayTracing: true,
    apiSupport: ['DirectX 12'],
  },
  {
    id: 'overwatch-2',
    name: 'Overwatch 2',
    genre: 'Hero Shooter',
    releaseYear: 2022,
    publisher: 'Blizzard Entertainment',
    baseFps: { '1080p': 258, '1440p': 185, '4k': 98 },
    gpuBound: 0.65,
    requirements: {
      minimum:     { cpuScore: 20, gpuScore: 15, ramGb: 8 },
      recommended: { cpuScore: 40, gpuScore: 38, ramGb: 8 },
      ultra:       { cpuScore: 65, gpuScore: 62, ramGb: 16 },
    },
    tags: ['fps', 'hero-shooter', 'competitive', 'esports', 'multiplayer'],
    isCompetitive: true,
    hasRayTracing: false,
    apiSupport: ['DirectX 11'],
  },
  {
    id: 'rainbow-six-siege',
    name: 'Rainbow Six Siege',
    genre: 'Tactical FPS',
    releaseYear: 2015,
    publisher: 'Ubisoft',
    baseFps: { '1080p': 215, '1440p': 155, '4k': 80 },
    gpuBound: 0.62,
    requirements: {
      minimum:     { cpuScore: 18, gpuScore: 15, ramGb: 8 },
      recommended: { cpuScore: 38, gpuScore: 35, ramGb: 8 },
      ultra:       { cpuScore: 62, gpuScore: 58, ramGb: 16 },
    },
    tags: ['fps', 'tactical', 'competitive', 'esports', 'multiplayer'],
    isCompetitive: true,
    hasRayTracing: false,
    apiSupport: ['Vulkan', 'DirectX 11'],
  },
  {
    id: 'league-of-legends',
    name: 'League of Legends',
    genre: 'MOBA',
    releaseYear: 2009,
    publisher: 'Riot Games',
    baseFps: { '1080p': 520, '1440p': 400, '4k': 220 },
    gpuBound: 0.50,
    requirements: {
      minimum:     { cpuScore: 12, gpuScore: 10, ramGb: 4 },
      recommended: { cpuScore: 28, gpuScore: 22, ramGb: 8 },
      ultra:       { cpuScore: 50, gpuScore: 45, ramGb: 16 },
    },
    tags: ['moba', 'competitive', 'esports', 'multiplayer', 'cpu-friendly'],
    isCompetitive: true,
    hasRayTracing: false,
    apiSupport: ['DirectX 11'],
  },
  {
    id: 'halo-infinite',
    name: 'Halo Infinite',
    genre: 'FPS / Sci-Fi',
    releaseYear: 2021,
    publisher: '343 Industries',
    baseFps: { '1080p': 125, '1440p': 88, '4k': 46 },
    gpuBound: 0.75,
    requirements: {
      minimum:     { cpuScore: 30, gpuScore: 28, ramGb: 8 },
      recommended: { cpuScore: 55, gpuScore: 60, ramGb: 16 },
      ultra:       { cpuScore: 80, gpuScore: 82, ramGb: 16 },
    },
    tags: ['fps', 'sci-fi', 'multiplayer', 'single-player'],
    isCompetitive: false,
    hasRayTracing: false,
    apiSupport: ['DirectX 12'],
  },
  // ─── MMO / Live Service ──────────────────────────────────────────────────────
  {
    id: 'world-of-warcraft',
    name: 'World of Warcraft',
    genre: 'MMORPG',
    releaseYear: 2004,
    publisher: 'Blizzard Entertainment',
    baseFps: { '1080p': 155, '1440p': 108, '4k': 56 },
    gpuBound: 0.65,
    requirements: {
      minimum:     { cpuScore: 18, gpuScore: 15, ramGb: 4 },
      recommended: { cpuScore: 42, gpuScore: 38, ramGb: 8 },
      ultra:       { cpuScore: 68, gpuScore: 65, ramGb: 16 },
    },
    tags: ['mmorpg', 'fantasy', 'multiplayer', 'social'],
    isCompetitive: false,
    hasRayTracing: false,
    apiSupport: ['DirectX 12'],
  },
  {
    id: 'final-fantasy-xiv',
    name: 'Final Fantasy XIV',
    genre: 'MMORPG',
    releaseYear: 2013,
    publisher: 'Square Enix',
    baseFps: { '1080p': 130, '1440p': 92, '4k': 50 },
    gpuBound: 0.68,
    requirements: {
      minimum:     { cpuScore: 18, gpuScore: 15, ramGb: 4 },
      recommended: { cpuScore: 42, gpuScore: 40, ramGb: 8 },
      ultra:       { cpuScore: 68, gpuScore: 65, ramGb: 16 },
    },
    tags: ['mmorpg', 'fantasy', 'multiplayer', 'social', 'story-rich'],
    isCompetitive: false,
    hasRayTracing: false,
    apiSupport: ['DirectX 11'],
  },
  {
    id: 'destiny-2',
    name: 'Destiny 2',
    genre: 'FPS / MMO',
    releaseYear: 2019,
    publisher: 'Bungie',
    baseFps: { '1080p': 155, '1440p': 108, '4k': 56 },
    gpuBound: 0.72,
    requirements: {
      minimum:     { cpuScore: 25, gpuScore: 22, ramGb: 6 },
      recommended: { cpuScore: 48, gpuScore: 48, ramGb: 8 },
      ultra:       { cpuScore: 72, gpuScore: 72, ramGb: 16 },
    },
    tags: ['fps', 'mmo', 'sci-fi', 'multiplayer', 'looter-shooter'],
    isCompetitive: false,
    hasRayTracing: false,
    apiSupport: ['DirectX 11'],
  },
  // ─── Indie / Mid-range ──────────────────────────────────────────────────────
  {
    id: 'minecraft',
    name: 'Minecraft (Modded)',
    genre: 'Sandbox / Survival',
    releaseYear: 2011,
    publisher: 'Mojang',
    baseFps: { '1080p': 130, '1440p': 98, '4k': 52 },
    gpuBound: 0.60,
    requirements: {
      minimum:     { cpuScore: 15, gpuScore: 12, ramGb: 4 },
      recommended: { cpuScore: 35, gpuScore: 30, ramGb: 16 },
      ultra:       { cpuScore: 65, gpuScore: 62, ramGb: 32 },
    },
    tags: ['sandbox', 'survival', 'creative', 'multiplayer', 'family-friendly'],
    isCompetitive: false,
    hasRayTracing: true,
    apiSupport: ['OpenGL'],
  },
  {
    id: 'stardew-valley',
    name: 'Stardew Valley',
    genre: 'Farming Simulator / RPG',
    releaseYear: 2016,
    publisher: 'ConcernedApe',
    baseFps: { '1080p': 500, '1440p': 500, '4k': 500 },
    gpuBound: 0.30,
    requirements: {
      minimum:     { cpuScore: 8, gpuScore: 5, ramGb: 2 },
      recommended: { cpuScore: 15, gpuScore: 10, ramGb: 4 },
      ultra:       { cpuScore: 25, gpuScore: 20, ramGb: 8 },
    },
    tags: ['simulation', 'rpg', 'farming', 'relaxing', 'multiplayer'],
    isCompetitive: false,
    hasRayTracing: false,
    apiSupport: ['DirectX 11', 'OpenGL'],
  },
  {
    id: 'cyberpunk-2077-phantom-liberty',
    name: 'Cyberpunk 2077: Phantom Liberty',
    genre: 'RPG / Open World',
    releaseYear: 2023,
    publisher: 'CD Projekt Red',
    baseFps: { '1080p': 78, '1440p': 52, '4k': 26 },
    gpuBound: 0.88,
    requirements: {
      minimum:     { cpuScore: 42, gpuScore: 38, ramGb: 8 },
      recommended: { cpuScore: 68, gpuScore: 72, ramGb: 16 },
      ultra:       { cpuScore: 90, gpuScore: 95, ramGb: 32 },
    },
    tags: ['open-world', 'rpg', 'ray-tracing', 'demanding', 'single-player', 'dlc'],
    isCompetitive: false,
    hasRayTracing: true,
    apiSupport: ['DirectX 12', 'Vulkan'],
  },
  {
    id: 'jedi-survivor',
    name: "Star Wars Jedi: Survivor",
    genre: 'Action / Adventure',
    releaseYear: 2023,
    publisher: 'Respawn Entertainment',
    baseFps: { '1080p': 68, '1440p': 46, '4k': 24 },
    gpuBound: 0.82,
    requirements: {
      minimum:     { cpuScore: 55, gpuScore: 52, ramGb: 8 },
      recommended: { cpuScore: 75, gpuScore: 75, ramGb: 16 },
      ultra:       { cpuScore: 90, gpuScore: 90, ramGb: 32 },
    },
    tags: ['action', 'adventure', 'star-wars', 'single-player'],
    isCompetitive: false,
    hasRayTracing: false,
    apiSupport: ['DirectX 12'],
  },
  {
    id: 'monster-hunter-wilds',
    name: 'Monster Hunter Wilds',
    genre: 'Action RPG',
    releaseYear: 2025,
    publisher: 'Capcom',
    baseFps: { '1080p': 72, '1440p': 50, '4k': 26 },
    gpuBound: 0.83,
    requirements: {
      minimum:     { cpuScore: 48, gpuScore: 52, ramGb: 16 },
      recommended: { cpuScore: 72, gpuScore: 75, ramGb: 16 },
      ultra:       { cpuScore: 88, gpuScore: 92, ramGb: 32 },
    },
    tags: ['action', 'rpg', 'multiplayer', 'co-op', 'demanding'],
    isCompetitive: false,
    hasRayTracing: true,
    apiSupport: ['DirectX 12'],
  },
  {
    id: 'path-of-exile-2',
    name: 'Path of Exile 2',
    genre: 'Action RPG / Hack and Slash',
    releaseYear: 2024,
    publisher: 'Grinding Gear Games',
    baseFps: { '1080p': 108, '1440p': 75, '4k': 40 },
    gpuBound: 0.72,
    requirements: {
      minimum:     { cpuScore: 28, gpuScore: 28, ramGb: 8 },
      recommended: { cpuScore: 55, gpuScore: 55, ramGb: 16 },
      ultra:       { cpuScore: 80, gpuScore: 78, ramGb: 32 },
    },
    tags: ['arpg', 'hack-and-slash', 'multiplayer', 'dark-fantasy'],
    isCompetitive: false,
    hasRayTracing: false,
    apiSupport: ['DirectX 12', 'Vulkan'],
  },
]

// Helper: get game by id
export function getGameById(id: string): Game | undefined {
  return GAMES.find(g => g.id === id)
}

// Helper: get games by genre
export function getGamesByGenre(genre: string): Game[] {
  return GAMES.filter(g => g.genre.toLowerCase().includes(genre.toLowerCase()))
}

// Helper: get games by tag
export function getGamesByTag(tag: string): Game[] {
  return GAMES.filter(g => g.tags.includes(tag))
}

// Competitive / esports focused games
export const COMPETITIVE_GAMES = GAMES.filter(g => g.isCompetitive)

// Demanding AAA games
export const DEMANDING_GAMES = GAMES.filter(g =>
  g.requirements.recommended.gpuScore >= 65
)
